### ISSUE TITLE
Question: Spicetify Config

### ISSUE THREAD

**Issue by ghost** [ikz87/dots-2.0#14]
I see you use wal-spotify to set spicetify values, what lead you to choosing that over using .config/spicetify to set these values?

**Comment by ikz87** [comment]
The colorscheme for spotify changes with the wallpaper as you probs know, and I made the wal-spotify script before I started using wpgtk templates, thus I used a shell script to change colors by sourcing the `~/.cache/wal/colors.sh` file. Now that you mention it, I probably should make a template for that too, just to have everything working in the same way, will do so in a couple hours when I'm free.
