### ISSUE TITLE
Question: how install this? help me plz

### ISSUE THREAD

**Issue by L1nker2** [ikz87/dots-2.0#15]
sory but i dont inderstent how install this. i will be happy if you help me with this <3

**Comment by ghost** [comment]
I've been working to get a streamlined install process up for myself I'll let you know when its working. You can watch my progress at https://github.com/dr-oofenshmirtz/Dots

I'm keeping an eye on issues here and at my fork. So if you run into problems share deets and I'll see what I can do. @ikz87 has been very active as well. Participating every day in my steps towards getting this up on my machine.

I'm also setting up mine to work in [nixos](https://nixos.org/). So if you're down to distro swap (or already use nix) once mine is up it'll be a `git clone` away.

The high level of installing this is putting these files in the right places and installing the right programs. However what exactly are the right programs is not 100% known. 

[Heres a stab at a dependencies look](https://github.com/ikz87/dots-2.0/issues/9) (its probably missing things and including things that aren't required)

**Comment by ghost** [comment]
Super rough, but more current than the deps issue. Here's what I've identified as dependencies https://github.com/dr-oofenshmirtz/configs/blob/main/nixos/deps.rice.nix#L45-L109

You also need the picom fork called out in the repo, not just picom

**Comment by ikz87** [comment]
Hey, sorry for the late reply.
Just finished making an install script, install process should be really streamlined now.
Be sure to still check @dr-oofenshmirtz repo for a different (and probably cleaner) install using nix
