### ISSUE TITLE
Scripts reference important/icons but it isn't in the repo

### ISSUE THREAD

**Issue by ghost** [ikz87/dots-2.0#17]
https://github.com/ikz87/dots-2.0/search?q=important%2Ficons

At least one other place references icons outside of the repo as well
https://github.com/ikz87/dots-2.0/blob/8f3e445b44eceaea6cd47689a2a28d9f903941c4/.config/dunst/dunstrc#L165-L166

**Comment by ghost** [comment]
Also thank you so much @ikz87 :heart:

**Comment by ikz87** [comment]
Totally forgot about the icons folder, just added it.
As for the dunstrc file, I think it would be best to just remove the uncommented line, this way dunst will (or at least should?) use the default icon pack set by the user.
Also, thank you too for helping out in noticing all the little wrong things in the repo <3
