### ISSUE TITLE
#question

### ISSUE THREAD

**Issue by L1nker2** [ikz87/dots-2.0#20]
hello, you are a very cool developer, I installed this on my arch. but that's not what I wanted. can you tell me how to make the same environment as in that video? or please make ready settings for this

**Comment by ikz87** [comment]
Please be more specific about the issue you're having

**Comment by L1nker2** [comment]
I wanted exactly these environment settings (wallpaper, theme, colors, etc.). is it possible to somehow get the rice settings config from this video?

**Comment by ikz87** [comment]
Just updated the default wallpaper to be the one first shown in the video. The colorscheme should also be the same.
Please try installing again and let me know if it worked

**Comment by L1nker2** [comment]
![2022-08-31_14:52:21](https://user-images.githubusercontent.com/107296755/187595573-20d5e49b-43ab-4820-9571-35521cb22783.png)
I installed it on a clean OS, connected all the dependencies through yay, as you wrote. but I still want to get the panel on top. please tell me how to install it? Or maybe you can throw off the config from that video?

**Comment by ikz87** [comment]
Please understand that I cannot be of much help without knowing exactly what is the root of the problem, however, I can think of a few things:
- eww is not installing correctly (this seems like the most likely)
- The install script somewhow is not working (although that doesn't seem to be the case)
- eww is not launching correctly from `.config/bspwm/autostart` (wouldn't make sense)

The image tells me very little about what could have gone wrong, you can try running `eww -c ~/.config/eww/mybar open bar_center` and showing me what it outputs. Also, is the status bar the only thing that's not working? Does rofi work for example? try launching an app with `super+shift+e` and see if it works.

**Comment by L1nker2** [comment]
sorry to bad request. rofi is work. im try inter to terminal this comand, but he return eror(
![2022-08-31_20:58:16](https://user-images.githubusercontent.com/107296755/187664838-0224e96f-560c-42bd-901b-fc8a564092ac.png)

**Comment by ikz87** [comment]
Check your eww config folder with `ls ~/.config/eww/mybar/` and show me if `eww.yuck` and `eww.scss` exist in that directory.

**Comment by L1nker2** [comment]
![image](https://user-images.githubusercontent.com/107296755/188077655-92d7c8c1-ce1b-4ef0-a174-1488d951b238.png)
yes

**Comment by ikz87** [comment]
Are the contents of those files the same as the files in the repo? It should work if that's the case

**Comment by L1nker2** [comment]
yes they are exactly the same

**Comment by ysef05** [comment]
hey!!! rice god... , eww is not working same here i tried to manually start it and this happend 

````[ysef@asus ~]$ eww -c ~/.config/eww/mybar open bar_right
eww -c ~/.config/eww/mybar open bar_center
eww -c ~/.config/eww/mybar open bar_left
failed to open window `bar_right`

Caused by:
    No window named 'bar_right' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `bar_center`

Caused by:
    No window named 'bar_center' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `bar_left`

Caused by:
    No window named 'bar_left' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.````

**Comment by ikz87** [comment]
Sorry for the late reply.
Went out and tried running this on a fresh arch install, that consists of:
- A user with the name "testing2"
- Only the packages from the dependency list of the repo
- Configs provided by running `install sh`

I just logged into Xorg and everything worked fine. Here's a screenshot of me starting the central bar manually just to show it works:
![image](https://user-images.githubusercontent.com/98569017/188260973-68aa43ea-15fa-4eca-aca5-a2d7062b97f9.png)

I haven't (and probably won't) found a way of replicating/fixing your issue, not sure what else I can tell you :(

**Comment by JustGold3n** [comment]
Hi, I ran in same isue as @YousefM8, but I was able to figure it out. In my case it was due to small error in declaring variables in file "~/.config/eww/eww.yuck". There is "(defvar battery_image "images/battery_normal.png")" two times first on line 16, then on 19. After deleting one, it shuld work.

**Comment by ysef05** [comment]
@ikz87 sorry i was sleeping..... i did the command like the picture but it says 

`no window naed 'bar_center' exists in config.`

**Comment by ysef05** [comment]
i will redo everything and test i will comment back if same issue

**Comment by ysef05** [comment]
hey!!!! everyone good new i know what the problem
here i fixed it in eww.yuck 

in line 16 and 19 there is (defvar battery_image "images/battery_normal.png") remove one of them remove line 16 or 19

**Comment by ysef05** [comment]
https://github.com/ikz87/dots-2.0/compare/main...YousefM8:dots-2.0:patch-1

**Comment by ikz87** [comment]
Thank you @JustGold3n and @YousefM8 for figuring out the issue, kinda weird that It doesn't seem to stop me from running the bar on my end, but hey, that's eww for ya.
Now, @YousefM8 I will merge your patch, but be aware that the change needs to be made in `.config/wpg/templates/eww_mybar_eww.yuck.base` too since wpgtk rewrites the eww config everytime the window manager is reset, I will do that myself in the repo.

**Comment by ysef05** [comment]
No problem.... rice god you let me use your rice, i help you by supporting your work :)

**Comment by ikz87** [comment]
Just fixed both files, I would advice to update and reinstall the rice just in case since I've changed a couple things in the last couple days. 
I guess this finally solves the issue, will be closing it now
