### ISSUE TITLE
a big problem)

### ISSUE THREAD

**Issue by L1nker2** [ikz87/dots-2.0#22]
hello friend, i know i'm already bored with you, but help again please) i installed it on a brand new arch, everything worked out yes, but because of my small monitor, my center bar shifts or closes the right bar. can you tell me how to fix this, or remove some elements from the central bar (well, or completely disable the central bar)

**Comment by ikz87** [comment]
If you want to resize anything you'd have to play around with the `eww.yuck` and `eww.scss` files in `./config/eww/mybar/` as I have mentioned in another issue here https://github.com/ikz87/dots-2.0/issues/6#issuecomment-1216032622

But if all you want is to remove the central bar completely, you can just not open it in 
`./config/bspwm/autostart` by commenting or deleting line 29, like this
![image](https://user-images.githubusercontent.com/98569017/188302475-caa462f8-5b6b-455d-82af-f37f97545987.png)

**Comment by L1nker2** [comment]
ok thanks, i'll play. because i deleted line 29 in autostart and the right bar didn't show up like that

**Comment by L1nker2** [comment]
I edit the file eww.yuck, save the changes. but after reboot they get up as it was according to the standard.

**Comment by ikz87** [comment]
Oh, I forgot, whenever you restart the window manager wpgtk rewrites the contents of mosts configs following the templates it has. I suggest you read about how wpgtk works and edit templates accorgdingly [here](https://github.com/deviantfero/wpgtk)

**Comment by L1nker2** [comment]
ok, trying to change the configs was a bad idea, nothing worked. I'll try changing the resolution. can you tell me which one you had?

**Comment by ikz87** [comment]
I use a 1080p monitor, everything in the rice is made for 1080p

**Comment by L1nker2** [comment]
thx, rice god)

**Comment by L1nker2** [comment]
good luck
