### ISSUE TITLE
tray_icon.ini

### ISSUE THREAD

**Issue by gh0stzk** [ikz87/dots-2.0#24]
Didnt work? i try to implement but no works

**Comment by ikz87** [comment]
What does running `polybar -c ~/.config/eww/mybar/polybar_tray.ini` manually output to you?

**Comment by gh0stzk** [comment]
Sorry my bad i tried just testing with "telegram" with ur default config in polybar_tray.ini and telegram tray doesnt show, but now i test with other apps and works fine. But no telegram, so i change height from 40 to 25 and it works. So i added to your config this options;

tray-maxsize = 16
tray-scale = 1.0
And now all trays works fine no matter the size of the polybar height.

also added 
override-redirect = true

because in my setup adding this polybar hack, make my all other windows shrink to not interfere with polybar, with that option bspwm doesnt respect polybar and everything  looks like must be.

thanks for ur work.
