### ISSUE TITLE
"Phantom" window when BSPWM restarts 

### ISSUE THREAD

**Issue by ikz87** [ikz87/dots-2.0#36]
When restarting BSPWM there's a chance for an empty window (or just receptacle?) to appear.
![image](https://user-images.githubusercontent.com/53365857/221887984-3bed881a-8841-492a-8d4f-736a3d185db2.png)
This window can't be closed normally and can't really be interacted with. 
This happens at random (as far as I know) so I'm not able to reproduce it freely.

If you happen to encounter this issue please try the following:
```
for wid in `xdotool search --class eww`; do xdotool windowunmap $wid; done
```

My guess is that for some reason, sometimes eww's root application window, a window that should always remain hidden, gets mapped to the screen.

If the above fix doesn't work, please try the following:
```
for id in `bspc query -N -n .leaf.\!window`; do bspc node $id -k; done;
```
This should work if the empty space is a receptacle instead of an actual window.

Please let me know if any of this fixes it because it's been literal months since the last time I was able to reproduce this behavior.

Any idea on how to reproduce this is also welcome.

**Comment by awarewen** [comment]
> When restarting BSPWM there's a chance for an empty window (or just receptacle?) to appear. ![image](https://user-images.githubusercontent.com/53365857/221887984-3bed881a-8841-492a-8d4f-736a3d185db2.png) This window can't be closed normally and can't really be interacted with. This happens at random (as far as I know) so I'm not able to reproduce it freely.
> 
> If you happen to encounter this issue please try the following:
> 
> ```
> for wid in `xdotool search --class eww`; do xdotool windowunmap $wid; done
> ```
> 
> My guess is that for some reason, sometimes eww's root application window, a window that should always remain hidden, gets mapped to the screen.
> 
> If the above fix doesn't work, please try the following:
> 
> ```
> for id in `bspc query -N -n .leaf.\!window`; do bspc node $id -k; done;
> ```
> 
> This should work if the empty space is a receptacle instead of an actual window.
> 
> Please let me know if any of this fixes it because it's been literal months since the last time I was able to reproduce this behavior.
> 
> Any idea on how to reproduce this is also welcome.

i well try.

**Comment by awarewen** [comment]
I tried the two commands you provided, and I still couldn't close the occupied windows manually, but I'm sure it wasn't 'Eww' that did it. These blanks have no window class names, and they can not be detected by the 'xdotool' and 'xprop' tools. I ran the detected commands on all of my desktops, and there was no abnormal output.

And this holdup automatically disappears when I run the 'bspc wm -r' command again (multiple times) . This is the information I have so far.

I will continue to dig deeper to find out why this is happening.

- 'xprop':


```
#!/bin/bash

window_ids=$(xprop -root _NET_CLIENT_LIST_STACKING | awk -F ', ' '{print $2}')
for id in $window_ids; do

    window_class=$(xprop -id $id | awk '/WM_CLASS/{print $4}')

    window_name=$(xprop -id $id | awk '/WM_NAME/{print substr($0, index($0,$2))}')

    window_title=$(xprop -id $id | awk '/_NET_WM_NAME/{print substr($0, index($0,$3))}')

    echo "Window ID: $id"
    echo "Class Name: $window_class"
    echo "Window Name: $window_name"
    echo "Title: $window_title"
    echo "----------------------------------------"
done
```

- 'xdotool':

```
#!/bin/bash

window_ids=$(xdotool search --desktop $(xdotool get_desktop) "" 2>/dev/null)

for id in $window_ids; do
 
    window_class=$(xdotool getwindowname $id)

    window_name=$(xdotool getwindowpid $id | xargs ps -o comm= 2>/dev/null)

    window_title=$(xdotool getwindowname $id)

    echo "Window ID: $id"
    echo "Class Name: $window_class"
    echo "Window Name: $window_name"
    echo "Title: $window_title"
    echo "----------------------------------------"
done
```

**Comment by awarewen** [comment]
I think I've found a possible cause for this: after 'BSPC WM-R' has popped up a blank space window several times, continue 'BSPC WM-R' until the space window closes automatically, 'picom' will automatically stop running, which may be a good breakthrough point.

I added the 'Killall Picom' command in to `.config/bspwm/autostart` script, which effectively prevents the blank window from popping up, but also introduces some new issues.

**Comment by awarewen** [comment]
![image](https://user-images.githubusercontent.com/53365857/222477897-8cf2f9d2-ddd7-401c-a4f0-d9ac56db9bb8.png)


...skipping...
Mar 02 23:46:01 Archlinux-gpd kernel: picom[3109742]: segfault at 18 ip 0000555e67c67dc1 sp 00007fffb2b33f28 error 6 in picom[555e67c37000+43000] likely on CPU 2 (core 2, socket 0)
Mar 02 23:46:01 Archlinux-gpd kernel: Code: 00 00 f2 0f 11 42 08 c3 90 8b 01 89 42 28 8b 41 04 89 42 2c b8 01 00 00 00 c3 0f 1f 80 00 00 00 00 f2 0f 10 01 b8 01 00 00 00 <f2> 0f 11 4>
Mar 02 23:46:01 Archlinux-gpd systemd[1]: Started Process Core Dump (PID 3110068/UID 0).
░░ Subject: A start job for unit systemd-coredump@2-3110068-0.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit systemd-coredump@2-3110068-0.service has finished successfully.
░░ 
░░ The job identifier is 3146.
Mar 02 23:46:01 Archlinux-gpd NetworkManager[1681370]: <info>  [1677771961.2352] agent-manager: agent[93c289ca39ca1d36,:1.207887/org.freedesktop.nm-applet/1000]: agent registered
Mar 02 23:46:01 Archlinux-gpd systemd-coredump[3110070]: [🡕] Process 3109742 (picom) of user 1000 dumped core.
                                                         
                                                         Stack trace of thread 3109742:
                                                         #0  0x0000555e67c67dc1 n/a (picom + 0x3bdc1)
                                                         #1  0x0000555e67c6bf3f n/a (picom + 0x3ff3f)
                                                         #2  0x0000555e67c3d836 n/a (picom + 0x11836)
                                                         #3  0x0000555e67c3e8dc n/a (picom + 0x128dc)
                                                         #4  0x00007f66ca38b0cb ev_invoke_pending (libev.so.4 + 0x50cb)
                                                         #5  0x00007f66ca38ed10 ev_run (libev.so.4 + 0x8d10)
                                                         #6  0x0000555e67c38b01 n/a (picom + 0xcb01)
                                                         #7  0x00007f66c9d71790 n/a (libc.so.6 + 0x23790)
                                                         #8  0x00007f66c9d7184a __libc_start_main (libc.so.6 + 0x2384a)
                                                         #9  0x0000555e67c39f95 n/a (picom + 0xdf95)
                                                         
                                                         Stack trace of thread 3109755:
                                                         #0  0x00007f66c9dd0766 n/a (libc.so.6 + 0x82766)
                                                         #1  0x00007f66c9dd2f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                         #2  0x00007f66c770c4ee n/a (iris_dri.so + 0x10c4ee)
                                                         #3  0x00007f66c76bc8bc n/a (iris_dri.so + 0xbc8bc)
                                                         #4  0x00007f66c770c41c n/a (iris_dri.so + 0x10c41c)
                                                         #5  0x00007f66c9dd3bb5 n/a (libc.so.6 + 0x85bb5)
                                                         #6  0x00007f66c9e55d90 n/a (libc.so.6 + 0x107d90)
                                                         
                                                         Stack trace of thread 3109757:
                                                         #0  0x00007f66c9dd0766 n/a (libc.so.6 + 0x82766)
                                                         #1  0x00007f66c9dd2f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                         #2  0x00007f66c770c4ee n/a (iris_dri.so + 0x10c4ee)
                                                         #3  0x00007f66c76bc8bc n/a (iris_dri.so + 0xbc8bc)
                                                         #4  0x00007f66c770c41c n/a (iris_dri.so + 0x10c41c)
                                                         #5  0x00007f66c9dd3bb5 n/a (libc.so.6 + 0x85bb5)

**Comment by awarewen** [comment]
The problem with the blank window hasn't occurred since I added 'Killall Picom' into `autostart` script . The new problem is that running 'BSPC WM-R' repeatedly causes 'picom' to crash, but it can be solved by rerunning 'picom' .

If you are still interested in solving the problem, you can continue to open this issue.

**Comment by ikz87** [comment]
I think it would be really weird for picom to be causing this, but since I am not able to reproduce the bug (Been trying for like 20 mins lol) I'll trust you. 

Just pushed b6ce8e5, now picom will be killed and re run on every bspwm restart. 

Will close this but I'm not 100% sure the issue is fixed. Please add a comment on this if you encounter this bug again, I will reopen the issue.
