### ISSUE TITLE
Post-Installation help

### ISSUE THREAD

**Issue by the-merky** [ikz87/dots-2.0#37]
So installed everything and when I run startx I just get an error. 
`... line 54: xterm: command not foundxinit:connection to X ser` Then the error just goes off screen.

**Comment by ikz87** [comment]
You need to set up your `.xinitrc` to run bspwm when it starts. 
First copy the template to your home directory:
```
cp /etc/X11/xinit/xinitrc ~/.xinitrc
```
Then delete all `xterm` and `xclock` related lines and append the following at the end of the file
```
exec bspwm
```

Then `bspwm` should start when you run `startx`

Check the [arch wiki](https://wiki.archlinux.org/title/xinit) for more info on how xinit works.

Let me know if you manage to get things working

**Comment by the-merky** [comment]
My screen went blank for a like 30 seconds when I ran startx and I started writing the new complaint, when the desktop just appeared!!! Just like in the screenshots! Thank you so much!

**Comment by ikz87** [comment]
I'm glad you managed to get it working! Though the blank screen for 30 seconds thing is a little weird, if it happens every time you start Xorg there might be something going on, if that's the case, feel free to open another issue for that specifically.

Closing now :)
