### ISSUE TITLE
Brightness controls stuck at 17% 

### ISSUE THREAD

**Issue by the-merky** [ikz87/dots-2.0#40]
When I use the shortcut in the `README` for adjusting the brightness. It shows a nice indicator, but it always stays at 17%, seemingly not changing the actual screen brightness. I checked the `sxhkdrc` and it runs a script with the up or the down argument. Interestingly, the volume controls seem to work fine.

**Comment by awarewen** [comment]
Did you install `light-git` Pkg? Please check if your user is in the video group and has permission to adjust the brightness. `usermod -aG video <user>`


> When I use the shortcut in the `README` for adjusting the brightness. It shows a nice indicator, but it always stays at 17%, seemingly not changing the actual screen brightness. I checked the `sxhkdrc` and it runs a script with the up or the down argument. Interestingly, the volume controls seem to work fine.

**Comment by the-merky** [comment]
Installing the `light-git` pkg fixed it! Thank you!
