### ISSUE TITLE
Question for noob!?

### ISSUE THREAD

**Issue by longwasu** [ikz87/dots-2.0#44]
- Can you make a video for installation from sratch (clean arch). I try but get trouble with some dependencies.

**Comment by ikz87** [comment]
Not willing to do a full video considering you can't really record the screen while on a tty, besides, I'd say the install process is simple enough. 

If you could provide more details about the issue you're having I'd gladly help you out right here :)

**Comment by longwasu** [comment]
- Okay, I have new problem, arch linux lagging when the bar is activate. When I turn off the bar (eww --config /root/.config/eww/mybar close-all) no lag issue anymore.
- I use arch linux on physical machine.

**Comment by awarewen** [comment]
> * Okay, I have new problem, arch linux lagging when the bar is activate. When I turn off the bar (eww --config /root/.config/eww/mybar close-all) no lag issue anymore.
> 
>     * I use arch linux on physical machine.

You mean eww after start-up can cause archlinux caton?
Can you send your eww version?  And how do you start eww?
In my case i use the `eww` PKG, not the `eww-git`, but i didn't had this issue :>

**Comment by suwalong** [comment]
> > * Okay, I have new problem, arch linux lagging when the bar is activate. When I turn off the bar (eww --config /root/.config/eww/mybar close-all) no lag issue anymore.
> >   
> >   * I use arch linux on physical machine.
> 
> You mean eww after start-up can cause archlinux caton? Can you send your eww version? And how do you start eww? In my case i use the `eww` PKG, not the `eww-git`, but i didn't had this issue :>

-

**Comment by longwasu** [comment]
- Yes. I start eww then my Arch lagging. But when I try different config, it works normally
- I build eww from this https://aur.archlinux.org/packages/eww. I start eww by "eww --config ~/.config/eww/mybar open ..."

**Comment by ikz87** [comment]
Can you run `eww --config ~/.config/eww/mybar logs` and show the output here? Not really sure what could be causing the issue

**Comment by longwasu** [comment]
Here the output
![2023-04-16_15:37:13](https://user-images.githubusercontent.com/109895775/232261617-a2c89ea9-6627-4847-bef9-51df1082a6ae.png)

**Comment by ikz87** [comment]
The error there is due to some leftover "bad" code left from a previous version of my rice (will clean it up eventually), but it shouldn't be the cause of any major performance issues. 

Thinking about it a bit more carefully, I know for a fact that using chromium based web browsers might cause some issues with the left bar specifically if the [plasma integration extension](https://chrome.google.com/webstore/detail/plasma-integration/cimiefiiaegbelhefglklhhakcgmhkai?hl=es) isn't installed due to some bug with the `playerctl` command used to fetch media info. 

Does the problem only happen when you play media in chrome/brave?

**Comment by longwasu** [comment]
Lagging happen when I start the bar, drop FPS. Turn off the bar make it work normally

https://user-images.githubusercontent.com/109895775/232282207-c5ecdfd0-5889-4a9a-8107-c86289ac4d66.mp4

**Comment by ikz87** [comment]
The lag seems to spike every second or so, and I think I know what's happening

By looking at the bar, I can see that the CPU module is not really working, which means that the script fetching that info is having some trouble. The script uses `mpstat` to fetch the CPU usage, I'll need you to run it manually and show me the output to see what's wrong
``` 
mpstat 2
```

As an example, this is my output from the command:
![image](https://user-images.githubusercontent.com/98569017/232339821-479008b3-2c90-4c41-b8ed-ad672c7614fd.png)

The command continues to update my CPU usage info every 2~ seconds

**Comment by longwasu** [comment]
I have some problem with my computer, I will reopen this later.__

**Comment by longwasu** [comment]
I'm back. Here's my mpstat 2 output
![image](https://user-images.githubusercontent.com/109895775/235131493-def4f917-9d4f-4d26-b8d2-c7d01218efe2.png)

**Comment by ikz87** [comment]
Weird,it seems to work correctly.
Run the following 
```
 mpstat 2 | while read line; do echo $line | awk '{printf "%s\n", $4}'; done
```
See if the output is right, and also check if running that one command causes FPS drops.

Not gonna lie, I'm kinda lost on this one :/

**Comment by longwasu** [comment]
Here the output
![image](https://user-images.githubusercontent.com/109895775/235295026-916f1d73-41a8-4de9-b668-e5e6cd2748b0.png)

When the command running, everything works normal. No FPS drop issue.

**Comment by ikz87** [comment]
Then I have no clue what else we could be causing it honestly

In the video you showed it happening when the central bar was open, does it happen when only the left or right bar are open too?

**Comment by longwasu** [comment]
No FPS drop when I open bar_left or bar_right. Seem only bar_center make lagging.
![image](https://user-images.githubusercontent.com/109895775/235361608-61e412f5-f96b-470b-b8ab-bf4ba38cc171.png)

**Comment by ikz87** [comment]
Ok that means that one of the scripts running in the center bar is causing the lag.
Please run the following commands one by one, and see which one of them is giving you trouble:
```
~/.config/eww/mybar/scripts/cpu_info
while true; do ~/.config/eww/mybar/scripts/ram_info --used; sleep 1; done
while true; do ~/.config/eww/mybar/scripts/temperature_info --used; sleep 1; done
while true; do ~/.config/eww/mybar/scripts/disk_info --used; sleep 1; done
while true; do ~/.config/eww/mybar/scripts/battery_info --percentage; sleep 1; done
```
You should do this with no eww daemon running (`killall eww` before testing the scripts)

**Comment by longwasu** [comment]
Oh, I see. Only the temperature_infor make lagging.
![image](https://user-images.githubusercontent.com/109895775/235574430-b34d7881-195e-418c-9561-df30751c5f5f.png)

**Comment by ikz87** [comment]
Sorry for the late reply, was busy during exam week.
Now that we found the problem we can start trying to work out a solution.

The temperature script depends on the `sensors` command. Run
```
sensors
``` 
And check if it works fine. You might need to follow this [guide](https://wiki.archlinux.org/title/lm_sensors#Setup) to set up things up, not so sure about that though

**Comment by longwasu** [comment]
Hello I'm back. This is the output of sensors command
![image](https://github.com/ikz87/dots-2.0/assets/109895775/49b22457-3a34-480f-b82b-0a2f802fd9b6)

**Comment by ikz87** [comment]
Does the following also cause lag?
```
while true; do sensors; sleep 1; done
```
If it does, the issue is beyond the scope of this repo and you should instead refer to the [lm-sensors](https://github.com/lm-sensors/lm-sensors) repo

**Comment by longwasu** [comment]
Yes it does, but I think I give up this rice here. Thanks for your enthusiastic help <3
