### ISSUE TITLE
Fix rofi details

### ISSUE THREAD

**Issue by JuanH88** [ikz87/dots-2.0#48]
![IMG_20230617_163233_edit_294903706923751](https://github.com/ikz87/dots-2.0/assets/127762766/0d5ca3ca-4f47-4312-8783-9928fd13d3c2)
I have noticed that there are a few small flaws or visual artifacts in rofi, window.rasi, logout.rasi and drun.rasi.  It seems to be a rofi problem, a solution to this is to replace "border: 5;"  by "border: 6;"  in window{} and element selected{}

**Comment by ikz87** [comment]
I knew about this and just thought rofi rounded corners didn't work correctly. I'm down to use a wider border for rofi if that means this will be fixed, will implement these changes rn, thank you!

**Comment by JuanH88** [comment]
Great, to keep the synergy you could make all "widgets" like calendar, music popup and rofi's have a 6px border, excluding eww bar or make the change completely to 6px. I already have it done, thanks for sharing your dotfiles🤗

**Comment by ikz87** [comment]
That's honestly quite a big change (even if it's just one pixel lol), but I'll think about it :)
