### ISSUE TITLE
Nothing works, only wallpaper shown

### ISSUE THREAD

**Issue by tomlidobnik** [ikz87/dots-2.0#49]
I followed the instructions to install the dotfiles, after restarting and logging in I could see the wallpaper but no keybinds work and nothing works. I use arch linux.

**Comment by ikz87** [comment]
Hi, I´d need some more info to help you with this, are you starting via `startx` on a TTY or are you using a display manager? It sounds like the `autostart` script is getting halted somewhere

**Comment by MostafaMohamed2002** [comment]
did you find any solution for it ?

**Comment by MostafaMohamed2002** [comment]
> did you find any solution for it ?

The problem is that I didn't have EWW installed.

**Comment by awarewen** [comment]
> > did you find any solution for it ?
> 
> The problem is that I didn't have EWW installed.

Please provide more information, such as: the startup method, whether the dependent package is installed completely, and whether the corresponding configuration file exists in the path
