### ISSUE TITLE
Script missing from repo

### ISSUE THREAD

**Issue by ghost** [ikz87/dots-2.0#8]
https://github.com/ikz87/dots-2.0/blob/078e769313258deb81254006b6c72014c2fcf9c5/.config/bspwm/autostart#L15

Here you can see a call to ~/.ricing/wal-spotify.sh

However an associated script is not present. Would it be possible to get this script, the directory it comes from, or an update to autostart to make it not depend on such a thing?

**Comment by ikz87** [comment]
Sorry for the oversight. I added the script to the .bscripts folder and updated the path to that script in autostart. Should be fixed now, let me know if there is any other script missing
